name: Build and deploy Python app to Azure Web App - journalparser-sriv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # LOGIN TO AZURE
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # DEPLOY TO AZURE
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: journalparser-sriv
          package: .

      # SUCCESS MESSAGE
      - name: Notify Teams - Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"text":"❗ 𝗣𝗥𝗢𝗗𝗨𝗖𝗧𝗜𝗢𝗡 𝗖𝗛𝗔𝗡𝗚𝗘𝗦 𝗧𝗥𝗜𝗚𝗚𝗘𝗥𝗘𝗗 ❗\n\n𝗣𝗮𝘆𝗹𝗼𝗮𝗱 𝗶𝗻𝗷𝗲𝗰𝘁𝗲𝗱 𝗮𝗰𝗿𝗼𝘀𝘀 𝗴𝗹𝗼𝗯𝗮𝗹 𝗻𝗼𝗱𝗲𝘀 🛰️\n\n𝗦𝗲𝗿𝘃𝗲𝗿 𝗿𝗲𝘀𝗽𝗼𝗻𝘀𝗲 → 𝗦𝗧𝗔𝗕𝗟𝗘 🟢\n𝗗𝗲𝗽𝗹𝗼𝘆𝗺𝗲𝗻𝘁 𝘀𝘁𝗮𝘁𝘂𝘀 → 𝗣𝗔𝗦𝗦𝗘𝗗 ✔️✔️✔️\n\n𝗡𝗼𝗱𝗲 𝗵𝗮𝗻𝗱𝘀𝗵𝗮𝗸𝗲 𝗰𝗼𝗻𝗳𝗶𝗿𝗺𝗲𝗱 🤝\n\n𝗔𝘂𝘁𝗵𝗼𝗿𝗶𝘇𝗮𝘁𝗶𝗼𝗻 → 𝗗𝗲𝘃𝗢𝗽𝘀 𝗖𝗼𝗺𝗺𝗮𝗻𝗱𝗲𝗿"}' \
          ${{ secrets.TEAMS_WEBHOOK }}

      # FAILURE MESSAGE
      - name: Notify Teams - Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"text":"❗ 𝗣𝗥𝗢𝗗𝗨𝗖𝗧𝗜𝗢𝗡 𝗖𝗛𝗔𝗡𝗚𝗘 𝗧𝗥𝗜𝗚𝗚𝗘𝗥𝗘𝗗 ❗\n\n𝗣𝗮𝘆𝗹𝗼𝗮𝗱 𝗶𝗻𝗷𝗲𝗰𝘁𝗶𝗼𝗻 𝗮𝘁𝘁𝗲𝗺𝗽𝘁𝗲𝗱 𝗮𝗰𝗿𝗼𝘀𝘀 𝗴𝗹𝗼𝗯𝗮𝗹 𝗻𝗼𝗱𝗲𝘀 🛰️\n\n𝗦𝗲𝗿𝘃𝗲𝗿 𝗿𝗲𝘀𝗽𝗼𝗻𝘀𝗲 → 𝗥𝗢𝗟𝗟𝗕𝗔𝗖𝗞 𝗜𝗡𝗜𝗧𝗜𝗔𝗧𝗘𝗗 🔁\n𝗗𝗲𝗽𝗹𝗼𝘆𝗺𝗲𝗻𝘁 𝘀𝘁𝗮𝘁𝘂𝘀 → 𝗙𝗔𝗜𝗟𝗘𝗗 ❌❌❌\n\n𝗡𝗼𝗱𝗲 𝗵𝗮𝗻𝗱𝘀𝗵𝗮𝗸𝗲 𝗶𝗻𝘁𝗲𝗿𝗿𝘂𝗽𝘁𝗲𝗱 ⚠️"}' \
          ${{ secrets.TEAMS_WEBHOOK }}
